### ISSUE TITLE
The uploader should confirm the sha of the files by re-downloading them from canvas after upload

### ISSUE THREAD

**Issue by davidawad** [alanfranz/canvas-submission-uploader#1]
Seemed somewhat straightforward, something every OMSCS student is "expected" to do, is go on, and clone the files after and make sure that they're the same. 

I'd love it if that were done automatically by this uploader.

**Comment by alanfranz** [comment]
Well, I usually re-download the file because I don't trust the manual upload, the problem should not arise with an automated system.

But, it's easy to implement so, why not? Give me a couple of days.
